config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  # get 'home/index'

  #get 'products' => 'products#index'
  #get 'products/:id' => 'products#show', as: 'product'

  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, :description, :price_in_cents, presence: true
  validates :price_in_cents, numericality: { only_integer: true }

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

  has_many :reviews

end

app/models/review.rb
class Review < ApplicationRecord
  validates :comment, presence: true
  validates :product_id, presence: true

  belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Your product has been successfully created!"
      redirect_to products_path
    else
      render new_product_path
      # render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Your product has been successfully updated!"
      redirect_to @product
    else
      # redirect_back_or_to @product
      # render edit_product_path(@product)
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Your product has been successfully DESTROYED!"
    redirect_to products_path
  end

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)

    if @review.save
      flash[:notice] = "Your review has been successfully created!"
      redirect_to products_path
    else
      render "products/show"
      # render new_product_path
      # render :new
    end
  end

  def edit
    @review = Review.find(params[:id]) # just added
    @product = Product.find(params[:product_id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Your review has been successfully updated!"
      redirect_to product_path(@product)
    else
      # redirect_back_or_to @product
      # render edit_product_path(@product)
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Your review has been successfully DESTROYED!"
    redirect_to root_path
  end

  def review_params
    params.require(:review).permit(:name, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'HOME', products_path %></li>
        <li><%= link_to 'NEW PRODUCT', new_product_path %></li>
      </ul>
    <nav>

      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :price_in_cents %>
    <%= f.text_area :price_in_cents %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/products/edit.html.erb
<h1>Editing <%= link_to @product.name, product_path(@product) %></h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1>All products</h1>

<% @products.each do |product| %>
  <div class="product">
    <h3>Name: <%= link_to product.name, product %></h3>
    Description: <%= product.description %><br />
    Price: <%= product.price_in_dollars %>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= link_to 'Show all products', products_path %>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>Description: <%= @product.description %></h3>
<h3>Price: <%= @product.price_in_dollars %></h3>

<%= link_to 'Edit Product', edit_product_path(@product) %>
| <%= link_to 'Delete Product', product_path(@product), method: :delete, data: {confirm: "Are you sure you want to delete the product '#{@product.name}'? This cannot be undone!"} %>


<h4>ADD New Review</h4>

<%= render 'reviews/form', review: @review %>


<h2>Reviews:</h2>
<ol>
  <% @product.reviews.each do |review| %>
    <li>
      <p> On <%= review.created_at %> <%= review.name %> said: </p>
      <p> <%= review.comment %> </p><p><%= link_to 'Edit Review', edit_product_review_path(@product, review) %></p>
    </li>
  <% end %>
</ol>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %><br />
    <%= f.label :comment %><br />
    <%= f.text_area :comment %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing</h1>

<%= render 'form', review: @review %>

<%= link_to 'Delete Review', product_review_path(@review), method: :delete, data: {confirm: "Are you sure you want to delete the review '#{@review.name}'? This cannot be undone!"} %>